#!/bin/bash
# cb-compton
# Openbox Pipe Menu for use with compton compositor
# Written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough <corenominal@corenominal.org>

if ! . cb-include.cfg &> /dev/null; then
    echo '  Failed to locate cb-include.cfg in PATH' >&2
    exit 1
fi

# ------------- Set xcompmgr command options -----------------------------------
if glxinfo | egrep -iq 'direct rendering: yes'; then
    EXECXCOMP='compton --vsync opengl'
else
    EXECXCOMP='compton'
fi

# Edit xcompmgr settings
if [[ $1 = '--edit' ]]; then
    if [[ ! -f ~/.config/compton.conf ]]; then
        cp '/etc/xdg/compton.conf' ~/.config/compton.conf
    fi
    if [[ -x /usr/bin/geany ]]; then
        geany ~/.config/compton.conf &
    else
        terminator --command='nano ~/.config/compton.conf'
    fi
    exit 0
fi

# Toggle compositing with compton. Called with "cb-compositor --toggle"
if [[ $1 = '--toggle' || $1 = '--start' ]]; then 
    if ! pidof compton > /dev/null; then
        $EXECXCOMP &
    else
        killall compton
    fi
    exit 0
fi

if [[ $1 = '--restart' ]]; then
    killall -q compton && sleep 1s
    cb-compositor --start
    exit 0
fi

if [[ $1 = '--watch' ]]; then
    while inotifywait -e modify ~/.config/compton.conf; do
        cb-compositor --restart
    done
    exit 0
fi

# Output Openbox menu
menuStart
if ! pidof compton > /dev/null; then
    menuItem 'Enable Compositing' 'cb-compositor --start'
else
    menuItem 'Restart Compositing' 'cb-compositor --restart'
    menuItem 'Disable Compositing' 'cb-compositor --toggle'
    menuSeparator
fi
menuItem 'Edit Compositing Settings' 'cb-compositor --edit'
menuEnd

exit 0
