#!/bin/bash
# ---------------------------------------------------------------------
# An Openbox pipemenu for use with LibreOffice and CrunchBang Linux.
# Written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
# ---------------------------------------------------------------------

if ! . cb-include.cfg 2> /dev/null; then
    echo '  Failed to locate cb-include.cfg in PATH' >&2
    exit 1
fi

if [[ $1 = '--install' ]]; then
    terminator --title='Install LibreOffice' --command='cb-libreoffice-pipemenu --install-lo'
    exit 0
fi

if [[ $1 = '--install-lo' ]]; then
    clear
    echo
    echo '  INSTALL LIBREOFFICE'
    echo '  -------------------'
    echo '  This script will install LibreOffice.'
    echo
    if prompt '  Run the installer now?'; then
        # Checking internet connection...
        connectiontest
        clear
        echo '  Updating sources...'
        sleep 2s
        sudo apt-get update
        clear
        while ! sudo apt-get install -y cb-meta-libreoffice; do
            clear
            echo
            echo '  There was a problem installing LibreOffice.'
            echo
            if prompt '  Hit any key to try again, or "q" to quit...' Q; then
                clear
                exit 0
            fi
        done
        clear
        echo
        echo '  LibreOffice has been installed successfully.'
        echo
        echo '  Hit any key to exit...'
        read -n1
    fi
    exit 0
fi

# Start pipemenu
menuStart

tools=( 'writer' 'calc' 'impress' 'draw' 'base' )

for curTool in "${tools[@]}"; do
    if [[ -x /usr/bin/lo$curTool ]]; then
        INSTALLED=true
        menuItem "${curTool^}" "lo$curTool"
    fi
done

if [[ ! $INSTALLED ]]; then
    menuItem 'Install LibreOffice' 'cb-libreoffice-pipemenu --install'
fi

# End pipemenu
menuEnd
exit 0
