#!/bin/bash
# ---------------------------------------------------------------------
# An Openbox pipemenu for use with LibreOffice and CrunchBang Linux.
# Written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
# ---------------------------------------------------------------------

pathto=$(readlink -f "$0" | sed 's%/*[^/]\+/*$%%')

if [[ -f $pathto/cb-include.cfg ]]; then # but what for?
    source "$pathto/cb-include.cfg"
else
    echo '  Failed to locate cb-include.cfg'
    exit 1
fi

if [[ $1 = '--install' ]]; then
    terminator --title='Install LibreOffice' --command='cb-libreoffice-pipemenu --install-lo'
    exit 0
fi

if [[ $1 = '--install-lo' ]]; then
    clear
    echo
    echo '  INSTALL LIBREOFFICE'
    echo '  -------------------'
    echo '  This script will install LibreOffice.'
    echo
    if prompt '  Run the installer now?'; then
        # Checking internet connection...
        connectiontest
        clear
        echo '  Updating sources...'
        sleep 2s
        sudo apt-get update
        clear
        while ! sudo apt-get install -y cb-meta-libreoffice; do
            clear
            echo
            echo '  There was a problem installing LibreOffice.'
            echo
            if prompt '  Hit any key to try again, or "q" to quit...' Q; then
                clear
                exit 0
            fi
        done
        clear
        echo
        echo '  LibreOffice has been installed successfully.'
        echo
        echo '  Hit any key to exit...'
        read -n1
    fi
    exit 0
fi
# Start pipemenu
menuStart

# Writer
if [[ -x /usr/bin/lowriter ]]; then
    INSTALLED=true
    menuItem 'Writer' 'lowriter'
fi

# Calc
if [[ -x /usr/bin/localc ]]; then
    INSTALLED=true
    menuItem 'Calc' 'localc'
fi

# Impress
if [[ -x /usr/bin/loimpress ]]; then
    INSTALLED=true
    menuItem 'Impress' 'loimpress'
fi

# Draw
if [[ -x /usr/bin/lodraw ]]; then
    INSTALLED=true
    menuItem 'Draw' 'lodraw'
fi

# Base
if [[ -x /usr/bin/lobase ]]; then
    INSTALLED=true
    menuItem 'Base' 'lobase'
fi

if [[ ! $INSTALLED ]]; then
    menuItem 'Install LibreOffice' 'cb-libreoffice-pipemenu --install'
fi

# End pipemenu
menuEnd
exit 0
