#!/bin/bash
# ---------------------------------------------------------------------
# An Openbox pipemenu for configuring printing under CrunchBang Linux.
# Written for CrunchBang Linux <http://crunchbanglinux.org/>
# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
# ---------------------------------------------------------------------

if ! . cb-include.cfg &> /dev/null; then
    echo '  Failed to locate cb-include.cfg in PATH' >&2
    exit 1
fi

if [[ $1 = '--install' ]]; then
    terminator --title='Install Printer Support' --command='cb-printing-pipemenu --install-printing'
    exit 0
fi
if [[ $1 = '--install-printing' ]]; then
    clear
    echo
    echo '  INSTALL PRINTING SUPPORT'
    echo '  ------------------------'
    echo '  This script will install printing support.'
    echo
    if prompt '  Run the installer now?'; then
        # Checking internet connection...
        connectiontest
        clear
        echo '  Updating sources...'
        sleep 2s
        sudo apt-get update
        clear
        if ! sudo apt-get install -y cb-meta-printer-support; then
            clear
            echo
            echo '  There was a problem installing printing packages.'
            echo
            if prompt '  Hit any key to try again, or "q" to quit...' Q; then
                clear
            else
                cb-printing-pipemenu --install-printing
            fi
        else
            clear
            echo
            echo '  Printing support has been installed successfully.'
            echo
            echo '  Hit any key to exit...'
            read -n1 a
        fi
    fi
    exit 0
fi

# Start pipemenu
menuStart

# check for system-config-printer
if [[ -x /usr/bin/system-config-printer ]]; then
    menuItem 'Configure Printers' 'gksudo system-config-printer'
else
    menuItem 'Install Printing Support' 'cb-printing-pipemenu --install'
fi

# End pipemenu
menuEnd

exit 0
