#!/bin/bash
# ---------------------------------------------------------------------
# An Openbox pipemenu for configuring printing under CrunchBang Linux.
# Written for CrunchBang Linux <http://crunchbanglinux.org/>
# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
# ---------------------------------------------------------------------

if ! . cb-include.cfg 2> /dev/null; then
    echo '  Failed to locate cb-include.cfg in PATH' >&2
    exit 1
fi

if [[ $1 = '--install' ]]; then
    terminator --title='Install Printer Support' --command='cb-printing-pipemenu --install-printing'
    
elif [[ $1 = '--install-printing' ]]; then
    promptInstall 'PRINTING SUPPORT' 'printing support' 'cb-meta-printer-support'
    
else
    # Pipemenu
    menuStart
    if [[ -x /usr/bin/system-config-printer ]]; then
        menuItem 'Configure Printers' 'gksudo system-config-printer'
    else
        menuItem 'Install Printing Support' 'cb-printing-pipemenu --install'
    fi
    menuEnd
fi
exit 0
