#!/bin/bash
# ---------------------------------------------------------------------
# Written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
# ---------------------------------------------------------------------

if ! . cb-include.cfg &> /dev/null; then
    echo '  Failed to locate cb-include.cfg in PATH' >&2
    exit 1
fi

if [[ $1 = '--viewer' ]]; then
    terminator --title='Install VNC Viewer' --command='cb-remote-desktop-pipemenu --install-viewer'
    exit 0
fi

if [[ $1 = '--server' ]]; then
    terminator --title='Install VNC Server' --command='cb-remote-desktop-pipemenu --install-server'
    exit 0
fi

if [[ $1 = '--install-viewer' ]]; then
    clear
    echo
    echo '  INSTALL REMOTE DESKTOP CLIENT'
    echo '  -----------------------------'
    echo '  This script will install TightVNC Viewer.'
    echo
    if prompt '  Run the installer now?'; then
        connectiontest
        
        #update sources
        echo '  Updating sources...'
		sleep 2s
		sudo apt-get update
		clear
        
        if ! sudo apt-get install -y xtightvncviewer; then
            clear
            echo
            echo '  There was a problem installing TightVNC viewer.'
            echo
            if prompt '  Hit any key to try again, or "q" to quit...' Q; then
                clear
            else
                cb-remote-desktop-pipemenu --install-viewer
            fi
        else
            clear
            echo
            echo '  TightVNC viewer has been installed successfully.'
            echo
            echo '  Hit any key to exit...'
            read -n1 a
        fi
    fi
    exit 0
fi

if [[ $1 = '--install-server' ]]; then
    clear
    echo
    echo '  INSTALL REMOTE DESKTOP SERVER'
    echo '  -----------------------------'
    echo '  This script will install Vino VNC server.'
    echo
    if prompt '  Run the installer now?'; then
        connectiontest
        
        #update sources
        echo '  Updating sources...'
		sleep 2s
		sudo apt-get update
		clear
        
        if ! sudo apt-get install -y vino; then
            clear
            echo
            echo '  There was a problem installing Vino VNC server.'
            echo
            if prompt '  Hit any key to try again, or "q" to quit...' Q; then
                clear
            else
                cb-remote-desktop-pipemenu --install-server
            fi
        else
            clear
            echo
            echo '  Vino VNC server has been installed successfully.'
            echo
            echo '  Hit any key to exit...'
            read -n1 a
        fi
    fi
    exit 0
fi

# Start pipemenu
menuStart

# Viewer
if [[ -x /usr/bin/xtightvncviewer ]]; then
    menuItem 'Viewer' 'vncviewer'
else
    menuItem 'Install Viewer' 'cb-remote-desktop-pipemenu --viewer'
fi

menuSeparator

# Server
if [[ -x /usr/lib/vino/vino-server ]]; then
	if pidof -s vino-server > /dev/null; then
        menuItem 'Stop VNC Server' 'killall vino-server'
	else
        menuItem 'Start VNC Server' '/usr/lib/vino/vino-server'
	fi
    menuItem 'VNC Server Preferences' 'vino-preferences'
else
    menuItem 'Install VNC Server' 'cb-remote-desktop-pipemenu --server'
fi

menuEnd

exit 0
