#!/bin/bash
# ---------------------------------------------------------------------
# Written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
# ---------------------------------------------------------------------

pathto=$(readlink -f "$0" | sed 's%/*[^/]\+/*$%%')

if [[ -f $pathto/cb-include.cfg ]]
then
    source "$pathto/cb-include.cfg"
else
    echo '  Failed to locate cb-include.cfg'
    exit 1
fi

I=0

if [[ $1 = '--viewer' ]]; then
    terminator --title='Install VNC Viewer' --command='cb-remote-desktop-pipemenu --install-viewer'
    exit 0
fi

if [[ $1 = '--server' ]]; then
    terminator --title='Install VNC Server' --command='cb-remote-desktop-pipemenu --install-server'
    exit 0
fi

if [[ $1 = '--install-viewer' ]]; then
    clear
    echo
    echo '  INSTALL REMOTE DESKTOP CLIENT'
    echo '  -----------------------------'
    echo '  This script will install TightVNC Viewer.'
    echo
    echo -n '  Run the installer now? (Y|n) > '
    read a
    if [[ ${a,} = "y" || ! $a ]]; then
        
        connectiontest
        
        #update sources
        echo '  Updating sources...'
		sleep 2s
		sudo apt-get update
		clear
        
        
        if ! sudo apt-get install -y xtightvncviewer; then
            clear
            echo
            echo '  There was a problem installing TightVNC viewer.'
            echo
            echo '  Hit any key to try again, or "q" to quit...'
            read -n1 a
            if [[ ${a,} = 'q' ]]; then
                clear
            else
                cb-remote-desktop-pipemenu --install-viewer
            fi
            exit 0
        else
            clear
            echo
            echo '  TightVNC viewer has been installed successfully.'
            echo
            echo '  Hit any key to exit...'
            read -n1 a
            exit 0
        fi
    fi
    exit 0
fi

if [[ $1 = '--install-server' ]]; then
    clear
    echo
    echo '  INSTALL REMOTE DESKTOP SERVER'
    echo '  -----------------------------'
    echo '  This script will install Vino VNC server.'
    echo
    echo -n '  Run the installer now? (Y|n) > '
    read a
    if [[ ${a,} = 'y' || ! $a ]]; then
        
        connectiontest
        
        #update sources
        echo '  Updating sources...'
		sleep 2s
		sudo apt-get update
		clear
        
        
        if ! sudo apt-get install -y vino; then
            clear
            echo
            echo '  There was a problem installing Vino VNC server.'
            echo
            echo '  Hit any key to try again, or "q" to quit...'
            read -n1 a
            if [[ ${a,} = "q" ]]; then
                clear
            else
                cb-remote-desktop-pipemenu --install-server
            fi
            exit 0
        else
            clear
            echo
            echo '  Vino VNC server has been installed successfully.'
            echo
            echo '  Hit any key to exit...'
            read -n1 a
            exit 0
        fi
    fi
    exit 0
fi

# Start pipemenu
menuStart

# Viewer
if [[ -x /usr/bin/xtightvncviewer ]];then
    menuItem 'Viewer' 'vncviewer'
else
    menuItem 'Install Viewer' 'cb-remote-desktop-pipemenu --viewer'
fi

menuSeparator

# Server
if [[ -x /usr/lib/vino/vino-server ]]; then
	if pidof -s vino-server > /dev/null; then
        menuItem 'Stop VNC Server' 'killall vino-server'
	else
        menuItem 'Start VNC Server' '/usr/lib/vino/vino-server'
	fi
    menuItem 'VNC Server Preferences' 'vino-preferences'
else
    menuItem 'Install VNC Server' 'cb-remote-desktop-pipemenu --server'
fi
menuEnd
exit 0
