#!/bin/bash
# ---------------------------------------------------------------------
# Written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
# ---------------------------------------------------------------------

if ! . cb-include.cfg &> /dev/null; then
    echo '  Failed to locate cb-include.cfg in PATH' >&2
    exit 1
fi

google_key_url_1='https://dl-ssl.google.com/linux/linux_signing_key.pub'
google_key_url_2='http://packages.crunchbang.org/waldorf-files/apt-keys/google-chrome.key'
opera_key_url_1='http://deb.opera.com/archive.key'
opera_key_url_2='http://packages.crunchbang.org/waldorf-files/apt-keys/opera.key'

if [[ $1 =~ ^--(chromium-browser|iceweasel|google-chrome|opera)$ ]]; then
    browserName=${1:2}
    browserName=${browserName//-/ }
    terminator --title="Install ${browserName~}" --command="cb-x-www-browser-pipemenu --install${1:1}"
    exit 0
fi

if [[ $1 = '--install-chromium-browser'  ]]; then
    clear
    echo
    echo '  INSTALL CHROMIUM BROWSER'
    echo '  ------------------------'
    echo '  This script will install Chromium.'
    echo
    if prompt '  Run the installer now?'; then
        connectiontest
        clear
        echo '  Updating sources...'
		sleep 2s
		sudo apt-get update
		clear
        
        if ! sudo apt-get install -y chromium-browser; then
            clear
            echo
            echo '  There was a problem installing Chromium.'
            echo
            if prompt '  Hit any key to try again, or "q" to quit...' Q; then
                clear
            else
                cb-x-www-browser-pipemenu --install-chromium-browser
            fi
        else
            clear
            echo
            echo '  Chromium has been installed successfully.'
            echo
            echo '  Hit any key to exit...'
            read -n1 a
        fi
    fi
    exit 0
fi

if [[ $1 = '--install-iceweasel' ]]; then
    clear
    echo
    echo '  INSTALL ICEWEASEL BROWSER'
    echo '  -------------------------'
    echo '  This script will install Iceweasel.'
    echo
    prompt '  Run the installer now?'
        connectiontest
        clear
        echo '  Updating sources...'
		sleep 2s
		sudo apt-get update
		clear
        
        if ! sudo apt-get install -y iceweasel; then
            clear
            echo
            echo '  There was a problem installing Iceweasel.'
            echo
            if prompt '  Hit any key to try again, or "q" to quit...' Q
                clear
            else
                cb-x-www-browser-pipemenu --install-iceweasel
            fi
        else
            clear
            echo
            echo '  Iceweasel has been installed successfully.'
            echo
            echo '  Hit any key to exit...'
            read -n1 a
        fi
    fi
    exit 0
fi

if [[ $1 = '--install-google-chrome' ]]; then
    clear
    echo
    echo '  INSTALL GOOGLE CHROME WWW BROWSER'
    echo '  ---------------------------------'
    echo '  This script will install Google Chrome.'
    echo
    if prompt '  Run the installer now?'; then
        connectiontest
        
        #add apt-key
        clear
        echo '  Adding APT key...'
        sleep 2s
        if ! wget -O google.key "$google_key_url_1" 2> /dev/null; then
            # Fallback to packages.crunchbang.org.
            if ! wget -O google.key "$google_key_url_2" 2> /dev/null; then
                echo '  Failed to retrieve APT key from Google Inc.'
                clear
                exit 1
            fi
        fi
        sudo apt-key add google.key
        rm -f google.key
        
        #create sources file
        echo '  Creating APT sources file...'
        sleep 2s
        if [[ -f /etc/apt/sources.list.d/google-chrome.list ]]; then
            sudo rm -f '/etc/apt/sources.list.d/google-chrome.list'
        fi
        echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee -a '/etc/apt/sources.list.d/google-chrome.list'
        
        #update sources
        echo '  Updating sources...'
		sleep 2s
		sudo apt-get update
		clear
        
        if ! sudo apt-get install -y google-chrome-stable; then
            clear
            echo
            echo '  There was a problem installing Google Chrome.'
            echo
            if prompt '  Hit any key to try again, or "q" to quit...' Q; then
                clear
            else
                cb-x-www-browser-pipemenu --install-google-chrome
            fi
        else
            clear
            echo
            echo '  Google Chrome has been installed successfully.'
            echo
            echo '  Hit any key to exit...'
            read -n1 a
        fi
    fi
    exit 0
fi

if [[ $1 = '--install-opera' ]]; then
    clear
    echo
    echo '  INSTALL OPERA WWW BROWSER'
    echo '  -------------------------'
    echo '  This script will install Opera.'
    echo
    if prompt '  Run the installer now?'; then        
        connectiontest
        
        #add apt-key
        clear
        echo '  Adding APT key...'
        sleep 2s
        if ! wget -O opera.key "$opera_key_url_1" 2> /dev/null; then
            # Fallback to packages.crunchbang.org.
            if ! wget -O opera.key "$opera_key_url_2" 2> /dev/null; then
                echo '  Failed to retrieve APT key from Opera Software ASA.'
                clear
                exit 1
            fi
        fi
        sudo apt-key add opera.key
        rm -f opera.key
        
        #create sources file
        echo '  Creating APT sources file...'
        sleep 2s
        if [[ -f /etc/apt/sources.list.d/opera.list ]]; then
            sudo rm -f '/etc/apt/sources.list.d/opera.list'
        fi
        echo 'deb http://deb.opera.com/opera/ stable non-free' | sudo tee -a /etc/apt/sources.list.d/opera.list
        #update sources
        echo '  Updating sources...'
		sleep 2s
		sudo apt-get update
		clear
        
        if ! sudo apt-get install -y opera; then
            clear
            echo
            echo '  There was a problem installing Opera.'
            echo
            if prompt '  Hit any key to try again, or "q" to quit...' Q; then
                clear
            else
                cb-x-www-browser-pipemenu --install-opera
            fi
        else
            clear
            echo
            echo '  Opera has been installed successfully.'
            echo
            echo '  Hit any key to exit...'
            read -n1 a
        fi
    fi
    exit 0
fi

# Start pipemenu
menuStart

tools=( 'chromium-browser' 'iceweasel' 'google-chrome' 'opera' )

for curTool in "${tools[@]}"; do
    curToolName=${curTool//-/ }
    curToolName=${curToolName~}
    if [[ -x /usr/bin/$curTool ]]; then
        INSTALLED=true
        menuItem "$curToolName" "$curTool"
        [[ $curToolName =~ 'Chrom' ]] && menuItem "$curToolName (Private Mode)" "$curTool --incognito"
    else
        menuItem "Install $curToolName" "cb-x-www-browser-pipemenu --$curTool"
    fi
done

# Configure default
if [[ $INSTALLED ]]; then
    menuSeparator
    menuItem 'Select default browser' 'terminator --command="sudo update-alternatives --config x-www-browser"'
fi
# End pipemenu
menuEnd
exit 0
